# Er wordt gebruik gemaakt van Jekyll & Just The Docs
remote_theme: pmarsceill/just-the-docs

title: 5G = Corona
description: >- # this means to ignore newlines until "baseurl:"
  Voor de puzzel "5G = Corona" wordt er een auto bestuurd doorheen de escaperoom om de locatie waar de 5G vandaan komt te vinden.
  Door middel van 8 LEDjes kan de afstand tot die locatie afgelezen worden.
color_scheme: dark
search_enabled: true
footer_content: "Glen Smet & Lisa De Vuyst - 3ELICTes - 2021"